### ISSUE TITLE
missing  / private link to preprocessing information

### ISSUE THREAD

**Issue by mtwebb** [IVRL/DSR#1]
Head's up that a few of the links in the readme are unreachable:
"The implementation of data preprocessing and registration is provided [here](https://github.com/IVRL/DronePrivate/tree/main/DroneSR-X7)."

same with: https://github.com/IVRL/DSR/blob/main/datasets/DSR/train_valid_test_split.json

I'm looking forward to seeing this aspect of your paper if it is available.

**Comment by doublemul** [comment]
The links are updated and be public.
